services:
    nginx:
        container_name: app_nginx
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        ports:
            - 80:80
        volumes:
            - ../:/var/www/html
            - ./nginx/conf.d:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - app-network

    app:
        container_name: app_php
        build:
            context: .
            dockerfile: ./app/Dockerfile
        volumes:
            - ../:/var/www/html
        depends_on:
            - db
        networks:
            - app-network

    db:
        container_name: app_db
        build:
            context: .
            dockerfile: ./db/Dockerfile
        restart: always
        volumes:
            - ../tmp/db/:/var/lib/mysql
        environment:
            MYSQL_DATABASE: test_project
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8101:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
